import Head from 'next/head';

import { Button } from '@/components/Button';

import VercelLogo from '../../public/vercel.svg';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Home Page</h1>
        <VercelLogo />
        <Button />
      </main>
    </div>
  );
}
